### ISSUE TITLE
Flag "Row Deleted"

### ISSUE THREAD

**Issue by fallGamlet** [chenwb-m/DBFKit#1]
Fore first, sorry for my english))
I found, that you parser class DBFParser is not read field flag "Deleted Row" in zero byte in each record (page link: http://ulisse.elettra.trieste.it/services/doc/dbase/DBFstruct.htm).

The records follow the header in the table file. Data records are preceded by one byte, that is, a space (20h) if the record is not deleted, an asterisk (2Ah) if the record is deleted. Fields are packed into records without field separators orrecord terminators. The end of the file is marked by a single byte, with the end-of-file marker, an OEM code page character value of 26 (1Ah). You can input OEM code page data as indicated below.

And, I replace some code for read this flag field: 
<code>
for (point = _i = _ref = this.headOffset, _ref1 = this.recordLength; _ref1 > 0 ? _i <= endPoint : _i >= endPoint; point = _i += _ref1) {
        if (!(point < bufferLength)) {
          continue;
        }
        bufferTemp = buffer.slice(point, point + this.recordLength);
        record = [];
        i = 0;
        // curPoint start with 1, not with curPoint = 0 ( after zero byte).
        curPoint = 1;
        // detect row deleted flag. If zero byte = 2Ah, then row releted
        __is_deleted__ = (bufferTemp[0] == 42 || bufferTemp[0] == '*');
        _ref2 = this.fields;
        for (_j = 0, _len = _ref2.length; _j < _len; _j++) {
          field = _ref2[_j];
          if (field.name === '') {
            curPoint += field.length;
          } else {
            record[i++] = this._parseField(curPoint, curPoint += field.length, field, bufferTemp);
          }
        }
        // add flag as field flag
        record.push({name: '_deleted_', value: **is_deleted** });
        _results.push(this.emit('record', record));
      }
</code>
If i did help, I happy))

**Comment by chenwb-m** [comment]
I am sorry that I just see your message. First, thank you very much for your help.Your suggestion is realy helpful and I have just corrected.
Have a nice day!
